In [3]:
import baostock as bs
import pandas as pd 
import numpy as np

In [6]:
 def get_codes_by_date():
        bs.login()
        date = '2021-04-12'
        stock_rs = bs.query_all_stock(date)
        stock_df = stock_rs.get_data()
        stock_df = stock_df[stock_df.code>='sh.600000']
        stock_df = stock_df[stock_df.code<='sz.399000']
        stock_df = stock_df.reset_index()
        print(stock_df)
        return stock_df

In [8]:
stock_df = get_codes_by_date()

login success!
      index       code tradeStatus code_name
0       220  sh.600000           1      浦发银行
1       221  sh.600004           1      白云机场
2       222  sh.600006           1      东风汽车
3       223  sh.600007           1      中国国贸
4       224  sh.600008           1      首创股份
...     ...        ...         ...       ...
4247   4467  sz.300965           1      恒宇信通
4248   4468  sz.300966           1      共同药业
4249   4469  sz.300969           1      恒帅股份
4250   4470  sz.300970           1      华绿生物
4251   4471  sz.300999           1       金龙鱼

[4252 rows x 4 columns]

In [ ]:
for index,row in stock_df.iterrows():

In [11]:
stock_df.index

RangeIndex(start=0, stop=4252, step=1)

In [ ]:
df_code.to_csv(f'{self.output_dir}/{row["code"]}.csv', index=False)

In [ ]:
/Users/senlinlidewo/pyprogram/dianping_zz/股票日行情dataset

In [12]:
a =  pd.read_csv('/Users/senlinlidewo/pyprogram/dianping_zz/股票日行情dataset/sz.300999.金龙鱼.csv')

In [13]:
a.columns

Index(['date', 'code', 'open', 'high', 'low', 'close', 'volume', 'amount',
       'adjustflag', 'turn', 'tradestatus', 'pctChg', 'peTTM', 'pbMRQ',
       'psTTM', 'pcfNcfTTM', 'isST'],
      dtype='object')

In [21]:
b = ['date', 'code', 'day_open', 'day_high', 'day_low', 'day_close', 'day_volume', 'day_amount',
       'day_adjustflag', 'day_turn', 'day_tradestatus', 'day_pctChg', 'day_peTTM', 'day_pbMRQ',
       'day_psTTM', 'day_pcfNcfTTM', 'day_isST']

['date',
 'code',
 'day_open',
 'day_high',
 'day_low',
 'day_close',
 'day_volume',
 'day_amount',
 'day_adjustflag',
 'day_turn',
 'day_tradestatus',
 'day_pctChg',
 'day_peTTM',
 'day_pbMRQ',
 'day_psTTM',
 'day_pcfNcfTTM',
 'day_isST']

In [11]:
c = ['open', 'high', 'low', 'close', 'volume', 'amount','new1','turn']

In [15]:
a.columns = b

In [16]:
a.head()

,date,code,day_open,day_high,day_low,day_close,day_volume,day_amount,day_adjustflag,day_turn,day_tradestatus,day_pctChg,day_peTTM,day_pbMRQ,day_psTTM,day_pcfNcfTTM,day_isST
0,2020-10-15,sz.300999,48.96,62.65,39.51,56.00,254037494,1.121627e+10,3,71.2112,1,117.8988,44.524916,4.524859,1.695843,28.694942,0
1,2020-10-16,sz.300999,49.00,55.87,48.01,49.01,182576747,9.291298e+09,3,51.1795,1,-12.4821,38.967253,3.960060,1.484165,25.113198,0
2,2020-10-19,sz.300999,47.00,47.50,44.89,45.20,114784503,5.269686e+09,3,32.1761,1,-7.7739,35.937968,3.652208,1.368787,23.160917,0
3,2020-10-20,sz.300999,45.40,49.20,45.40,47.90,108170712,5.132022e+09,3,30.3221,1,5.9735,38.084705,3.870371,1.450551,24.544423,0
4,2020-10-21,sz.300999,47.00,50.14,45.90,47.50,115243544,5.539717e+09,3,32.3048,1,-0.8351,37.766670,3.838050,1.438438,24.339459,0

In [26]:
ma=7
a['week_'+str(ma)]=a['day_open'].rolling(ma).mean()
a[:20]

,date,code,day_open,day_high,day_low,day_close,day_volume,day_amount,day_adjustflag,day_turn,day_tradestatus,day_pctChg,day_peTTM,day_pbMRQ,day_psTTM,day_pcfNcfTTM,day_isST,ma_7,week_7
0,2020-10-15,sz.300999,48.96,62.65,39.51,56.00,254037494,1.121627e+10,3,71.2112,1,117.8988,44.524916,4.524859,1.695843,28.694942,0,NaN,NaN
1,2020-10-16,sz.300999,49.00,55.87,48.01,49.01,182576747,9.291298e+09,3,51.1795,1,-12.4821,38.967253,3.960060,1.484165,25.113198,0,NaN,NaN
2,2020-10-19,sz.300999,47.00,47.50,44.89,45.20,114784503,5.269686e+09,3,32.1761,1,-7.7739,35.937968,3.652208,1.368787,23.160917,0,NaN,NaN
3,2020-10-20,sz.300999,45.40,49.20,45.40,47.90,108170712,5.132022e+09,3,30.3221,1,5.9735,38.084705,3.870371,1.450551,24.544423,0,NaN,NaN
4,2020-10-21,sz.300999,47.00,50.14,45.90,47.50,115243544,5.539717e+09,3,32.3048,1,-0.8351,37.766670,3.838050,1.438438,24.339459,0,NaN,NaN
5,2020-10-22,sz.300999,46.81,49.87,46.52,48.65,86663090,4.198743e+09,3,24.2932,1,2.4211,38.681021,3.930972,1.473263,24.928731,0,NaN,NaN
6,2020-10-23,sz.300999,49.23,49.48,47.35,47.90,74395457,3.592974e+09,3,20.8543,1,-1.5416,38.084705,3.870371,1.450551,24.544423,0,NaN,47.628571
7,2020-10-26,sz.300999,47.35,47.48,45.85,46.39,51756998,2.410432e+09,3,14.5084,1,-3.1524,36.884123,3.748361,1.404824,23.770685,0,NaN,47.398571
8,2020-10-27,sz.300999,46.05,46.30,43.72,44.53,72361323,3.242065e+09,3,20.2841,1,-4.0095,35.405259,3.598071,1.348498,22.817603,0,47.628571,46.977143
9,2020-10-28,sz.300999,44.30,45.50,43.85,45.30,52824162,2.367255e+09,3,14.8075,1,1.7292,36.017477,3.660288,1.371816,23.212158,0,47.398571,46.591429
10,2020-10-29,sz.300999,44.31,45.17,44.06,44.47,41707292,1.860893e+09,3,11.6913,1,-1.8322,35.357554,3.593223,1.346681,22.786858,0,46.977143,46.435714
11,2020-10-30,sz.300999,44.63,47.88,44.63,45.99,76467265,3.533502e+09,3,21.4351,1,3.4180,36.566087,3.716041,1.392711,23.565721,0,46.591429,46.097143
12,2020-11-02,sz.300999,48.00,52.37,47.00,51.65,119153657,5.887609e+09,3,33.4009,1,12.3070,39.953636,4.055648,1.510214,31.550607,0,46.435714,46.267143
13,2020-11-03,sz.300999,51.28,54.41,50.45,51.16,106681430,5.573437e+09,3,29.9047,1,-0.9487,39.574598,4.017173,1.495887,31.251288,0,46.097143,46.560000
14,2020-11-04,sz.300999,51.80,54.28,51.05,53.74,92860870,4.897243e+09,3,26.0305,1,5.0430,41.570346,4.219759,1.571324,32.827292,0,46.267143,47.195714
15,2020-11-05,sz.300999,53.40,56.66,52.25,53.90,97970002,5.300962e+09,3,27.4627,1,0.2977,41.694113,4.232322,1.576003,32.925028,0,46.560000,48.245714
16,2020-11-06,sz.300999,53.90,61.50,53.48,60.90,109924453,6.256618e+09,3,30.8137,1,12.9870,47.108933,4.781974,1.780678,37.201006,0,47.195714,49.617143
17,2020-11-09,sz.300999,61.00,64.64,58.58,61.66,110605581,6.256618e+09,3,31.0047,1,1.2479,47.696828,4.841651,1.802900,37.665255,0,48.245714,52.001429
18,2020-11-10,sz.300999,61.66,65.89,60.23,63.69,93708096,5.945302e+09,3,26.2680,1,3.2922,49.267126,5.001050,1.862256,38.905289,0,49.617143,54.434286
19,2020-11-11,sz.300999,62.66,66.55,59.13,60.18,108239803,6.910152e+09,3,30.3415,1,-5.5111,46.551980,4.725439,1.759626,36.761191,0,52.001429,56.528571

In [30]:
a.week_7 = a.week_7.shift(1)
a[:20]

,date,code,day_open,day_high,day_low,day_close,day_volume,day_amount,day_adjustflag,day_turn,day_tradestatus,day_pctChg,day_peTTM,day_pbMRQ,day_psTTM,day_pcfNcfTTM,day_isST,ma_7,week_7
0,2020-10-15,sz.300999,48.96,62.65,39.51,56.00,254037494,1.121627e+10,3,71.2112,1,117.8988,44.524916,4.524859,1.695843,28.694942,0,NaN,NaN
1,2020-10-16,sz.300999,49.00,55.87,48.01,49.01,182576747,9.291298e+09,3,51.1795,1,-12.4821,38.967253,3.960060,1.484165,25.113198,0,NaN,NaN
2,2020-10-19,sz.300999,47.00,47.50,44.89,45.20,114784503,5.269686e+09,3,32.1761,1,-7.7739,35.937968,3.652208,1.368787,23.160917,0,NaN,NaN
3,2020-10-20,sz.300999,45.40,49.20,45.40,47.90,108170712,5.132022e+09,3,30.3221,1,5.9735,38.084705,3.870371,1.450551,24.544423,0,NaN,NaN
4,2020-10-21,sz.300999,47.00,50.14,45.90,47.50,115243544,5.539717e+09,3,32.3048,1,-0.8351,37.766670,3.838050,1.438438,24.339459,0,NaN,NaN
5,2020-10-22,sz.300999,46.81,49.87,46.52,48.65,86663090,4.198743e+09,3,24.2932,1,2.4211,38.681021,3.930972,1.473263,24.928731,0,NaN,NaN
6,2020-10-23,sz.300999,49.23,49.48,47.35,47.90,74395457,3.592974e+09,3,20.8543,1,-1.5416,38.084705,3.870371,1.450551,24.544423,0,NaN,NaN
7,2020-10-26,sz.300999,47.35,47.48,45.85,46.39,51756998,2.410432e+09,3,14.5084,1,-3.1524,36.884123,3.748361,1.404824,23.770685,0,NaN,47.628571
8,2020-10-27,sz.300999,46.05,46.30,43.72,44.53,72361323,3.242065e+09,3,20.2841,1,-4.0095,35.405259,3.598071,1.348498,22.817603,0,47.628571,47.398571
9,2020-10-28,sz.300999,44.30,45.50,43.85,45.30,52824162,2.367255e+09,3,14.8075,1,1.7292,36.017477,3.660288,1.371816,23.212158,0,47.398571,46.977143
10,2020-10-29,sz.300999,44.31,45.17,44.06,44.47,41707292,1.860893e+09,3,11.6913,1,-1.8322,35.357554,3.593223,1.346681,22.786858,0,46.977143,46.591429
11,2020-10-30,sz.300999,44.63,47.88,44.63,45.99,76467265,3.533502e+09,3,21.4351,1,3.4180,36.566087,3.716041,1.392711,23.565721,0,46.591429,46.435714
12,2020-11-02,sz.300999,48.00,52.37,47.00,51.65,119153657,5.887609e+09,3,33.4009,1,12.3070,39.953636,4.055648,1.510214,31.550607,0,46.435714,46.097143
13,2020-11-03,sz.300999,51.28,54.41,50.45,51.16,106681430,5.573437e+09,3,29.9047,1,-0.9487,39.574598,4.017173,1.495887,31.251288,0,46.097143,46.267143
14,2020-11-04,sz.300999,51.80,54.28,51.05,53.74,92860870,4.897243e+09,3,26.0305,1,5.0430,41.570346,4.219759,1.571324,32.827292,0,46.267143,46.560000
15,2020-11-05,sz.300999,53.40,56.66,52.25,53.90,97970002,5.300962e+09,3,27.4627,1,0.2977,41.694113,4.232322,1.576003,32.925028,0,46.560000,47.195714
16,2020-11-06,sz.300999,53.90,61.50,53.48,60.90,109924453,6.256618e+09,3,30.8137,1,12.9870,47.108933,4.781974,1.780678,37.201006,0,47.195714,48.245714
17,2020-11-09,sz.300999,61.00,64.64,58.58,61.66,110605581,6.256618e+09,3,31.0047,1,1.2479,47.696828,4.841651,1.802900,37.665255,0,48.245714,49.617143
18,2020-11-10,sz.300999,61.66,65.89,60.23,63.69,93708096,5.945302e+09,3,26.2680,1,3.2922,49.267126,5.001050,1.862256,38.905289,0,49.617143,52.001429
19,2020-11-11,sz.300999,62.66,66.55,59.13,60.18,108239803,6.910152e+09,3,30.3415,1,-5.5111,46.551980,4.725439,1.759626,36.761191,0,52.001429,54.434286

In [21]:
sum(a.day_open[0:7])/7

47.62857142857143

In [ ]:
df_v = dt[['data']].shift(1) 
df_v.columns = ['test] 
dt = concat([dt, df_v], axis=1)

In [ ]:
#第二个函数要打开指定名称的csv
#第三个函数要循环生成新的列。
#第四个函数要把新生成的列shift1.

In [60]:
 def get_codes_by_date():
        bs.login()
        date = '2021-04-12'
        stock_rs = bs.query_all_stock(date)
        stock_df = stock_rs.get_data()
        stock_df = stock_df[stock_df.code>='sh.600000']
        stock_df = stock_df[stock_df.code<='sz.399000']
        stock_df = stock_df.reset_index()
        return stock_df

In [61]:
def open_csv(path,row):
    dstdir = f'{path}/{row["code"]}.csv'
    df = pd.read_csv(dstdir)
    return df

In [62]:
def df_process(df):
    df['new'] = df['close']
    df.new = df.new.shift(1)
    df['price_change'] = df.close - df.new 
    df['price_change'][0]=df['close'][0]-df['open'][0]
    del df['new']
    return df

In [63]:
def rolling_mean(nums,df,columns):
    df[str(nums)+ columns] = df[i].rolling(nums).mean()
    #df[str(nums)+ columns] =  df[str(nums)+ columns].shift(1)
    return df

In [64]:
c = ['open', 'high', 'low', 'close', 'volume', 'amount','price_change','turn']

In [68]:
df = get_codes_by_date()
for index,row in df.iterrows():
    try:
        path = '/Users/senlinlidewo/pyprogram/dianping_zz/total_merge'
        df1 = open_csv(path,row)
        df2 = df_process(df1)
        for i in c:
            df3 = rolling_mean(15,df2,i)
        dstdir = f'{path}/{row["code"]}.csv'
        df3.to_csv(dstdir, index=False)
    except:
        continue

login success!

<ipython-input-62-dc3c1fe6a2d7>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['price_change'][0]=df['close'][0]-df['open'][0]

In [50]:
df =

login success!

In [58]:
m = pd.read_csv('/Users/senlinlidewo/pyprogram/dianping_zz/total_merge/sh.600000.csv')
m.shape

(5190, 70)

In [59]:
n = pd.read_csv('/Users/senlinlidewo/pyprogram/dianping_zz/total_merge/sh.600004.csv')
n.shape

(4363, 70)

In [56]:
cols = m.columns.difference(n.columns)
cols

Index(['3new1', 'new1'], dtype='object')

In [57]:
m = m.drop(['3new1', 'new1'],axis=1)
m.to_csv('/Users/senlinlidewo/pyprogram/dianping_zz/total_merge/sh.600000.csv',index=False)